// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id 'com.android.application' version '8.3.0' apply false // Updated to AGP 8.3.0
    id 'com.android.library' version '8.3.0' apply false // Updated to AGP 8.3.0
}

// Removing printlns for cleaner output now that JDK issue is understood
// println "Build Script Java Version: " + System.getProperty("java.version")
// println "Build Script Java Home: " + System.getProperty("java.home")

// allprojects {
//     project.afterEvaluate {
//         println "Evaluation Phase Project ${project.name} Java Version: " + System.getProperty("java.version")
//     }
// }
